$(document).ready(function() {
  $("button#javascript").click(function(){
    $("#js-text").toggle();
  });
  $("button#operators").click(function(){
    $("#operators-text").toggle();
  });$("button#variables").click(function(){
    $("#variables-text").toggle();
  });$("button#vnc").click(function(){
    $("#vnc-text").toggle();
  });$("button#functions").click(function(){
    $("#functions-text").toggle();
  });$("button#methods").click(function(){
    $("#methods-text").toggle();
  });$("button#arguments").click(function(){
    $("#arguments-text").toggle();
  });$("button#parameters").click(function(){
    $("#parameters-text").toggle();
  });$("button#return").click(function(){
    $("#return-text").toggle();
  });$("button#cm").click(function(){
    $("#cm-text").toggle();
  });$("button#strings").click(function(){
    $("#strings-text").toggle();
  });$("button#booleans").click(function(){
    $("#booleans-text").toggle();
  });$("button#undefined").click(function(){
    $("#undefined-text").toggle();
  });$("button#nan").click(function(){
    $("#nan-text").toggle();
  });$("button#escape").click(function(){
    $("#escape-text").toggle();
  });$("button#alert").click(function(){
    $("#alert-text").toggle();
  });$("button#comments").click(function(){
    $("#comments-text").toggle();
  });$("button#jquery").click(function(){
    $("#jquery-text").toggle();
  });$("button#attributes").click(function(){
    $("#attributes-text").toggle();
  });
});
